image_ingestion:
  root_dir: artifacts/data_ingestion
  url: https://user-images.githubusercontent.com/12981474/40157448-eff91f06-5953-11e8-9a37-f6b5693fa03f.png
  save_img_original: artifacts/data_ingestion/monkey.png
  save_img_low_res: artifacts/data_ingestion/monkey_low_res.png

image_enhance:
  load_img_low_res: artifacts/data_ingestion/monkey.png
  save_high_res_img: artifacts/data_ingestion/monkey_high_res.png

comparative_plot:
  load_img_low_res: artifacts/data_ingestion/monkey_low_res.png
  load_img_original: artifacts/data_ingestion/monkey.png
  load_img_high_res: artifacts/data_ingestion/monkey_high_res.png
  save_comp_plot: artifacts/data_ingestion/comparative_plot.png
  title: Low Resolution vs Original vs High Resolution